name: Trigger S3 Upload for Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable:
    uses: UnityGames-UPS/unity-build-pipeline/.github/workflows/main.yml@main
    with:
      s3_bucket: unity.build-prod
      s3_folder: SL-WOF
      cloudfront_distribution_id: EVFPZ9ROHP45P
      invalidate_paths: "/SL-WOF/*"
